version: '3.7'
services:
    kopia:
        image: kopia/kopia:latest
        hostname: Hostname
        container_name: Kopia
        restart: unless-stopped
        ports:
            - 51515:51515
        command: ["/bin/sh", "-c", "/app/config/init-kopia.sh"]
        environment:
            # Set repository password
            KOPIA_PASSWORD: "SECRET"
            USER: "User"
        volumes:
            # Mount local folders needed by kopia
            - /path/to/config/dir:/app/config
            - /path/to/cache/dir:/app/cache
            - /path/to/logs/dir:/app/logs
            # Mount local folders to snapshot
            - /path/to/data/dir:/data:ro
            # Mount repository location
            - /path/to/repository/dir:/repository
            # Mount path for browsing mounted snapshots
            - /path/to/tmp/dir:/tmp:shared
            # Mount Rclone configuration
            - /home/falah/.config/rclone:/config/rclone
            # Mount the initialization script
            - /path/to/init-kopia.sh:/app/config/init-kopia.sh
